
const BASE_URL = "http://localhost:3000";
export const products = [
  {
    category: "Clothes",
    sub_category: "Men's Wear",
    title: "Jeans",
    description: "Men High-Rise Relaxed Fit Modern Boot Denim Jeans",
    price: 200,
    rating: {
      rate: 4.5,
      count: 200,
    },
    image: `${BASE_URL}/images/jeans.jpg`,
  },
  {
    category: "Clothes",
    sub_category: "Men's Wear",
    title: "T-shirt",
    description: "Dubai Travel Group T-shirt Buy Online This is pack of 1 T-Shirts",
    price: 150,
    rating: {
      rate: 4.2,
      count: 150,
    },
    image: `${BASE_URL}/images/Tshirt.jpg`,
  },
  {
    category: "Clothes",
    sub_category: "Women's Wear",
    title: "SALWAR SUITS PAJAMAS CHUDIDHAR",
    description: "BHAUBALI COLLECTION CHUDIDAR/SALWAR SUIT UNSTITCHED MATERIAL. 1.SUIT MATERIAL ,PAIJAMA ALONG WITH SHAWL",
    price: 300,
    rating: {
      rate: 4.7,
      count: 220,
    },
    image: `${BASE_URL}/images/dress.jpeg`,
  },
  {
    category: "Clothes",
    sub_category: "Women's Wear",
    title: "Sits-Bark meroon semi silk saree",
    description: "A charming semi silk saree in a solid color in shades of dark maroon. ",
    price: 120,
    rating: {
      rate: 4.0,
      count: 180,
    },
    image: `${BASE_URL}/images/saree.jpg`,
  },
  {
    category: "Clothes",
    sub_category: "Women's Wear",
    title: "Women brown solid hooded puffer jacket",
    description: "Brown solid puffer jacket, has a mock collar, 2 pockets ,has a zip closure, long sleeves, straight hemline, polyester lining",
    price: 450,
    rating: {
      rate: 4.6,
      count: 100,
    },
    image: `${BASE_URL}/images/jacket.jpg`,
  },
  {
    category: "Electronics",
    sub_category: "Mobile Phones",
    title: "VivO Y28s 5g",
    description: "vivo Y28s 5G (Lavender, 128 GB)  (8 GB RAM)16.66 cm (6.56 inch)",
    price: 1000,
    rating: {
      rate: 4.8,
      count: 500,
    },
    image: `${BASE_URL}/images/vivoy28.jpg`,
  },
  {
    category: "Electronics",
    sub_category: "Mobile Phones",
    title: "Apple iPhone 14",
    description: "Apple iPhone 14 (512 GB) - Blue,Advanced camera system for better photos in any light",
    price: 10000,
    rating: {
      rate: 4.8,
      count: 500,
    },
    image: `${BASE_URL}/images/iphone.jpg`,
  },
  {
    category: "Electronics",
    sub_category: "Smart Watch",
    title: "T500 Android Smart Watch",
    description: "gauri enterprises T500 Android Smart Watch Men 4G Network BT Call GPS X8 Ultra Smartwatch  (Black Strap, Free Size)",
    price: 50,
    rating: {
      rate: 4.3,
      count: 300,
    },
    image: `${BASE_URL}/images/smartwatch.jpg`,
  },
  {
    category: "Electronics",
    sub_category: "Laptops",
    title: "HP Laptop",
    description: "HP Laptop 15s-fq3066TU 15.6inch HD, Intel Celeron N4500, 8GB RAM, 512GB SSD, Win 11, MS Off H&S 21, Jet Black, Free HP Wired Mouse",
    price: 1200,
    rating: {
      rate: 4.9,
      count: 150,
    },
    image: `${BASE_URL}/images/laptop.jpg`,
  },
  // {
  //   category: "Electronics",
  //   sub_category: "Laptops",
  //   title: "Laptop Sleeve",
  //   description: "protective sleeve for laptops",
  //   price: 30,
  //   rating: {
  //     rate: 4.1,
  //     count: 80,
  //   },
  //   image: `${BASE_URL}/images/sleeve.jpeg`,
  // },
  {
    category: "Electronics",
    sub_category: "Headphones",
    title: "Bluetooth",
    description: "Jxrev Wireless Bluetooth 5.3 Earbud Stereo Bass,Bluetooth Headphones In Ear Noise Cancelling Mic,Earphones I-Px7 Waterproof Sports,32H Playtime Usb C Mini Charging Case Ear Buds For Android Ios",
    price: 200,
    rating: {
      rate: 4.7,
      count: 400,
    },
    image: `${BASE_URL}/images/bluetooth.jpg`,
  },
  {
    category: "Appliances",
    sub_category: "Home Applainces",
    title: "Telivision",
    description: "40″ Full HD Smart TV Series A4KAU",
    price: 150,
    rating: {
      rate: 4.4,
      count: 220,
    },
    image: `${BASE_URL}/images/tv.jpg`,
  },
  {
    category: "Appliances",
    sub_category: "Home Applainces",
    title: "Fridge",
    description: "Intellifresh 308L 2 Star Frost Free Double-Door Refrigerator",
    price: 300,
    rating: {
      rate: 4.9,
      count: 130,
    },
    image: `${BASE_URL}/images/fridge.jpg`,
  },
  {
    category: "Appliances",
    sub_category: "Home Applainces",
    title: "Washing Machine",
    description: "Havells-Lloyd 8.5 Kg 5 Star Semi Automatic Top Load Washing Machine (LWMS85RK2 Red, F Shield Motor)",
    price: 250,
    rating: {
      rate: 4.6,
      count: 90,
    },
    image: `${BASE_URL}/images/washingmachine.jpg`,
  },
  {
    category: "Appliances",
    sub_category: "Home Applainces",
    title: "AC",
    description: "Amstrad Optima Series AC 1 Ton 3 Star Inverter Split Air Conditioner – AMSi1231C",
    price: 80,
    rating: {
      rate: 4.3,
      count: 350,
    },
    image: `${BASE_URL}/images/ac.jpg`,
  },
  {
    category: "Groceries",
    sub_category: "Snacks",
    title: "Lays",
    description: "Lay's Potato Chip Variety Pack, 40 Count, 1 oz Bags, Classic, Multi Pack",
    price: 5,
    rating: {
      rate: 4.8,
      count: 200,
    },
    image: `${BASE_URL}/images/lays.jpg`,
  },
  {
    category: "Groceries",
    sub_category: "Cooking & Baking Supplies",
    title: "Wheat Flour",
    description: "Aashirvaad Superior MP Atta, 100% Whole Wheat Flour, 0% Maida, 5kg/6kg (Weight may vary)",
    price: 2,
    rating: {
      rate: 4.6,
      count: 180,
    },
    image: `${BASE_URL}/images/wheatflour.jpeg`,
  },
  {
    category: "Groceries",
    sub_category: "Cooking and Baking Supplies",
    title: "Orange Juice",
    description: "Tata Salt 1 Kg, Free Flowing and Iodised Namak, Vacuum Evaporated, Salt in Fresh",
    price: 4,
    rating: {
      rate: 4.7,
      count: 300,
    },
    image: `${BASE_URL}/images/salt.jpg`,
  },
  {
    category: "Groceries",
    sub_category: "Fruits",
    title: "Strawberry",
    description: "Hybrid Strawberry – Sweet, Fresh, Healthy Red Fruit",
    price: 3,
    rating: {
      rate: 4.2,
      count: 400,
    },
    image: `${BASE_URL}/images/strawberry.jpg`,
  },
  {
    category: "Groceries",
    sub_category: "Snacks",
    title: "Chocolates",
    description: "Astonished Retail Assorted Chocolate with Handcrafted Metal Basket | Chocolate Gift Hamper for Diwali, Birthday, Holi, Rakhi, New Year, Christmas, Anniversary ",
    price: 10,
    rating: {
      rate: 4.5,
      count: 350,
    },
    image: `${BASE_URL}/images/chocolates.jpg`,
  },
];